### ISSUE TITLE
Different background color in full-screen mode

### ISSUE THREAD

**Issue by slideray** [qsmodo/sxiv#1]
Can you make or show how you can make a different variable background color in full-screen mode?

**Comment by qsmodo** [comment]
Sorry, only now did I see your open issues in this repository (I thought Github would mail me if any was opened).

Do you mean to create a new resource, say `fullscreenbackground`, that would set the fullscreen background to a different color than the normal background color? That seems very doable. I'll give it a try.

**Comment by qsmodo** [comment]
That is now available via `fsBackground` resource. I messed it up and did a force push without committing, that's why you don't see a commit addressing it.

**Comment by slideray** [comment]
I'm beyond grateful!
