### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by blogdemoi** [qsmodo/sxiv#3]
Hello,

How to uninstall?

Thank you.

**Comment by qsmodo** [comment]
Hello,

Just clone the repository and then

```
sudo make install
```

You may need to get dependencies. In Debian systems `apt build-dep sxiv` should do it.

Let me know if you need further help.

Also bear in mind there is https://github.com/nsxiv/nsxiv which is a much more featureful fork, and probably the de-facto one.

**Comment by blogdemoi** [comment]
Thank you, however my question was how to uninstall, not install. I wish to then install nsxiv.

**Comment by qsmodo** [comment]
sudo make uninstall
